- name: Install pre-reqs for docker module
  hosts: localhost
  connection: local
  tags: prereqs
  tasks:
    - name: Install requests module
      ansible.builtin.pip:
        name: requests < 2.32.0
- name: Create containers to use as ansible managed nodes
  hosts: localhost
  tasks:
    - name: Create container c1
      community.docker.docker_container:
        name: "c{{ item }}"
        image: python
        tty: true
        interactive: true
        # state: absent
      loop: "{{ range(1, 10) }}"
